# Refer to https://github.com/adfinis-sygroup/openshift-mariadb-galera

# Headless service for galera statefulset
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  namespace: ns-galera
  name: galera-hs
  labels:
    app: galera-ss
spec:
  ports:
  - port: 3306
    name: mysql
  clusterIP: None
  selector:
    app: galera-ss

---

# Client service for connecting to any MySQL instance for reads.
apiVersion: v1
kind: Service
metadata:
  namespace: ns-galera
  name: galera-svc
  labels:
    app: galera-ss
spec:
  ports:
  - port: 3306
    name: mysql
  selector:
    app: galera-ss

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: ns-galera
  name: galera-ss
spec:
  selector:
    matchLabels:
      app: galera-ss
  serviceName: "galera-hs"
  replicas: 3
  template:
    metadata:
      labels:
        app: galera-ss
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      securityContext:
        runAsUser: 27
        fsGroup: 27
      containers:
      - name: mariadb
        image: drlee001/k8s-mariadb-galera-centos:v004-k8s113org
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          privileged: true
        ports:
        - containerPort: 3306
          name: mysql
        - containerPort: 4444
          name: sst
        - containerPort: 4567
          name: replication
        - containerPort: 4568
          name: ist
        readinessProbe:
          exec:
            command:
            - /usr/share/container-scripts/mysql/readiness-probe.sh
          initialDelaySeconds: 15
          timeoutSeconds: 5
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/mysql
          subPath: data
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: MYSQL_USER
            value: mysql
          - name: MYSQL_PASSWORD
            value: mysql
          - name: MYSQL_DATABASE
            value: mydb
          - name: MYSQL_ROOT_PASSWORD
            value: mysql
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 200Mi
